// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0mqmt_7AW8QV7pJc0lj8CHTG8qAcGrD0',
    appId: '1:321266809329:web:ace32647dcdd9928226c50',
    messagingSenderId: '321266809329',
    projectId: 'flutter-fast-firebase',
    authDomain: 'flutter-fast-firebase.firebaseapp.com',
    storageBucket: 'flutter-fast-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA012DpZBXA64qQiP_5XawA11MtADcDH4M',
    appId: '1:321266809329:android:c70cf84960d3e6d3226c50',
    messagingSenderId: '321266809329',
    projectId: 'flutter-fast-firebase',
    storageBucket: 'flutter-fast-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO_5zUGkoemIJJoW7s31yqghQEVDOpbEg',
    appId: '1:321266809329:ios:b7eab69194bf52cf226c50',
    messagingSenderId: '321266809329',
    projectId: 'flutter-fast-firebase',
    storageBucket: 'flutter-fast-firebase.appspot.com',
    iosClientId: '321266809329-20n8j52qrjpvoa3sl0kkr95iv8au1eoo.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO_5zUGkoemIJJoW7s31yqghQEVDOpbEg',
    appId: '1:321266809329:ios:60e03efe69e39899226c50',
    messagingSenderId: '321266809329',
    projectId: 'flutter-fast-firebase',
    storageBucket: 'flutter-fast-firebase.appspot.com',
    iosClientId: '321266809329-056til6qamesiijbnddubkeu9qij2nc8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseSample.RunnerTests',
  );
}
